root: true
env:
  node: true
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
parserOptions:
  parser: "babel-eslint"
rules:
  - "prettier/prettier":
      - "error":
        singleQuote: true
        semi: false
